spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_accountpick?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123123  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
#    logging.level.org.springframework.boot.autoconfigure: error
logging:
  level:
    org.springframework.boot.autoconfigure: error
    com.pjboy.riddler_reserve.mapper: debug
debug: true

# 文件上传
file:
  basicURL: http://image.accountpick.com:8888/static
  uploadFolder: F:\static\
  img:
    imgList: .jpg,.png
    goodsContentImgSource: ${file.uploadFolder}/goods/content/images/
    goodsContentImgURL: ${file.basicURL}/goods/content/images/
    goodsCoverImgSource: ${file.uploadFolder}/goods/coverImage/
    goodsCoverImgURL: ${file.basicURL}/goods/coverImage/
